name: Deploy Docker Container

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}

    steps:
    - name: Debug Secrets
      run: |
        echo "Admin Secret is: ${HASURA_GRAPHQL_ADMIN_SECRET:+Set}"
      env:
        HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}

    - name: Checkout Repository with Submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Hasura CLI
      run: |
        curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
      shell: bash

    - name: Replace docker-compose.yml in PokeAPI
      run: |
        cp ./docker-compose.yml ./PokeAPI/docker-compose.yml

    - name: Run make install
      run: make install
      working-directory: ./PokeAPI

    - name: Run make setup
      run: make setup
      working-directory: ./PokeAPI

    - name: Run make docker-setup
      run: make docker-setup
      working-directory: ./PokeAPI

    - name: Run make hasura-apply
      env:
        HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
      run: make hasura-apply
      working-directory: ./PokeAPI
      
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Tag and Push Container
      run: |
        docker tag pokeapi-pokedex:latest ${{ secrets.DOCKER_HUB_USERNAME }}/pokeapi-pokedex:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/pokeapi-pokedex:latest
